ALTER TABLE people
ADD COLUMN is_deleted TINYINT(1);

UPDATE people SET is_deleted=true WHERE id=4;

ALTER TABLE people MODIFY is_deleted BIT;

ALTER TABLE people MODIFY id INT NOT NULL;

ALTER TABLE people DROP PRIMARY KEY;

ALTER TABLE people
ADD CONSTRAINT pk_id_name PRIMARY KEY (`id`, `name`);

ALTER TABLE people
ADD COLUMN `last_long_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE people DROP PRIMARY KEY;
ALTER TABLE people MODIFY id INT NOT NULL AUTO_INCREMENT,
ADD CONSTRAINT pk_people PRIMARY KEY(id),
ALTER TABLE people MODIFY name VARCHAR(50) UNIQUE;

TRUNCATE TABLE people;
